version: '3'

services:
  app:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=data4meuser
      - DB_PASSWORD=yourpassword
      - DB_NAME=data4meapi
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=data4meuser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=data4meapi
